ci: workaround for wokwi ci installation

diff --git a/.github/workflows/build-rust-no_std-hello-world.yaml b/.github/workflows/build-rust-no_std-hello-world.yaml
--- a/.github/workflows/build-rust-no_std-hello-world.yaml
+++ b/.github/workflows/build-rust-no_std-hello-world.yaml
@@ -31,12 +31,12 @@ jobs:
         id: get_upload_url
         run: |
           url=$(echo "$response" | jq -r '.upload_url' | sed 's/{?name,label}//')
-          echo "::set-output name=url::$url"
+          echo "url=$url" >> $GITHUB_OUTPUT
         env:
           response: ${{ steps.get_release.outputs.data }}
 
   build:
-    runs-on: ubuntu-20.04
+    runs-on: ubuntu-22.04
     container:
       image: espressif/idf-rust:all_1.75.0.0
       options: --user esp --workdir /home/esp
@@ -46,7 +46,18 @@ jobs:
         run: |
           export HOME=/home/esp
           cd /home/esp
+
+          set +e # Workaround for Exit code 2 exit code installation
           curl -L https://wokwi.com/ci/install.sh | sh
+          exit_code=$?
+          if [ $exit_code -eq 2 ]; then
+            echo "Received exit code 2 from install script, overriding to 0"
+            exit_code=0
+          else
+          exit $exit_code
+          fi
+          set -e
+
           pwd
           git clone --depth 1 --branch ${{ github.ref_name }} https://github.com/georgik/esp32-lang-lab.git esp32-lang-lab
       - name: Build and upload binaries
